## **Carga de los datos**

In [2]:
import pandas as pd
import plotly.express as px
import plotly.io as pio

# Si usas VS Code o Cursor (es el más estable):
pio.renderers.default = "vscode"

In [3]:
df = pd.read_csv('../data/Cantidad_anual_de_suicidios_reportados_en_el_Departamento_de_Antioquia_desde_2005_20260503.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   NombreMunicipio          2500 non-null   str
 1   CodigoMunicipio          2500 non-null   int64
 2   Ubicación                2500 non-null   str
 3   NombreRegion             2500 non-null   str
 4   CodigoRegion             2500 non-null   int64
 5   Anio                     2500 non-null   int64
 6   CausaMortalidad          2500 non-null   str
 7   TipoPoblacionObjetivo    2500 non-null   str
 8   NumeroPoblacionObjetivo  2500 non-null   str
 9   NumeroCasos              2500 non-null   int64
dtypes: int64(4), str(6)
memory usage: 195.4 KB

In [4]:
df.head()

,NombreMunicipio,CodigoMunicipio,Ubicación,NombreRegion,CodigoRegion,Anio,CausaMortalidad,TipoPoblacionObjetivo,NumeroPoblacionObjetivo,NumeroCasos
0,Abejorral,5002,POINT (-75.427045 5.79145),ORIENTE,7,2005,Suicidios,Poblacion total,"20,249",2
1,Abriaquí,5004,POINT (-76.064563 6.63197),OCCIDENTE,6,2005,Suicidios,Poblacion total,"2,690",0
2,Alejandría,5021,POINT (-75.141258 6.376923),ORIENTE,7,2005,Suicidios,Poblacion total,"3,816",0
3,Amagá,5030,POINT (-75.703216 6.04063),SUROESTE,8,2005,Suicidios,Poblacion total,"27,155",0
4,Amalfi,5031,POINT (-75.075028 6.907385),NORDESTE,4,2005,Suicidios,Poblacion total,"20,525",2

In [5]:
df.NombreRegion.value_counts()

NombreRegion
ORIENTE            460
SUROESTE           460
OCCIDENTE          380
NORTE              340
URABA              220
NORDESTE           200
VALLE DE ABURRA    200
BAJO CAUCA         120
MAGDALENA MEDIO    120
Name: count, dtype: int64

In [6]:
df.Anio.value_counts()

Anio
2005    125
2006    125
2007    125
2008    125
2009    125
2010    125
2011    125
2012    125
2013    125
2014    125
2015    125
2016    125
2017    125
2018    125
2019    125
2020    125
2021    125
2022    125
2023    125
2024    125
Name: count, dtype: int64

In [7]:
columnas_a_usar = [
    'NombreMunicipio',
    'NombreRegion',
    'Anio',
    'CausaMortalidad',
    'TipoPoblacionObjetivo',
    'NumeroPoblacionObjetivo',
    'NumeroCasos'
]

In [8]:
df_data = df[columnas_a_usar].copy()
df_data.head()

,NombreMunicipio,NombreRegion,Anio,CausaMortalidad,TipoPoblacionObjetivo,NumeroPoblacionObjetivo,NumeroCasos
0,Abejorral,ORIENTE,2005,Suicidios,Poblacion total,"20,249",2
1,Abriaquí,OCCIDENTE,2005,Suicidios,Poblacion total,"2,690",0
2,Alejandría,ORIENTE,2005,Suicidios,Poblacion total,"3,816",0
3,Amagá,SUROESTE,2005,Suicidios,Poblacion total,"27,155",0
4,Amalfi,NORDESTE,2005,Suicidios,Poblacion total,"20,525",2

In [9]:
df_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   NombreMunicipio          2500 non-null   str
 1   NombreRegion             2500 non-null   str
 2   Anio                     2500 non-null   int64
 3   CausaMortalidad          2500 non-null   str
 4   TipoPoblacionObjetivo    2500 non-null   str
 5   NumeroPoblacionObjetivo  2500 non-null   str
 6   NumeroCasos              2500 non-null   int64
dtypes: int64(2), str(5)
memory usage: 136.8 KB

## **EDA**

In [10]:
print('Dimensiones:',df_data.shape)

Dimensiones: (2500, 7)

In [11]:
print('Tipos de datos:')
df_data.dtypes

Tipos de datos:

NombreMunicipio              str
NombreRegion                 str
Anio                       int64
CausaMortalidad              str
TipoPoblacionObjetivo        str
NumeroPoblacionObjetivo      str
NumeroCasos                int64
dtype: object

In [12]:
df_data.isnull().sum(skipna=False)

NombreMunicipio            0
NombreRegion               0
Anio                       0
CausaMortalidad            0
TipoPoblacionObjetivo      0
NumeroPoblacionObjetivo    0
NumeroCasos                0
dtype: int64

In [13]:
print('cantidad de duplicados:',df_data.duplicated().sum())

cantidad de duplicados: 0

In [14]:
df_data.describe()

              Anio  NumeroCasos
count  2500.000000  2500.000000
mean   2014.500000     3.166400
std       5.767435    15.003438
min    2005.000000     0.000000
25%    2009.750000     0.000000
50%    2014.500000     1.000000
75%    2019.250000     2.000000
max    2024.000000   246.000000

## Conversion de datos

In [15]:
cols_categoricas = ['NombreMunicipio','NombreRegion']
df_data[cols_categoricas] = df_data[cols_categoricas].astype('category')
df_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   NombreMunicipio          2500 non-null   category
 1   NombreRegion             2500 non-null   category
 2   Anio                     2500 non-null   int64
 3   CausaMortalidad          2500 non-null   str
 4   TipoPoblacionObjetivo    2500 non-null   str
 5   NumeroPoblacionObjetivo  2500 non-null   str
 6   NumeroCasos              2500 non-null   int64
dtypes: category(2), int64(2), str(3)
memory usage: 103.7 KB

## Creacion de tablas

In [ ]:
pivot_table = pd.pivot_table(df_data, values='NumeroCasos', index='NombreMunicipio',columns='Anio', aggfunc='sum')
print(pivot_table)

In [23]:
group_table_casos = df_data.groupby('Anio')['NumeroCasos'].sum()
print(group_table_casos)

Anio
2005    327
2006    328
2007    296
2008    338
2009    335
2010    326
2011    325
2012    329
2013    330
2014    323
2015    374
2016    400
2017    392
2018    434
2019    476
2020    453
2021    488
2022    541
2023    586
2024    515
Name: NumeroCasos, dtype: int64

## Figuras y Graficos

In [24]:
fig = px.bar(df_data , x='Anio', y='NumeroCasos', title='Numero casos vs anios')
fig.show()